server:
  #tomcat运行端口
  port: 9991
spring:
  profiles:
    active: dev
  application:
    name: admin-server
  http:
    encoding:
      force: false
      enabled: true
      charset: utf-8
    multipart:
      #默认支持文件上传
      enabled: true
      #支持文件写入磁盘
      file-size-threshold: 0
      # 最大支持文件大小
      max-file-size: 100Mb
      # 最大支持请求大小
      max-request-size: 100Mb

#Feign服务
feign-client:
  user-server: user-server
  store-server: store-server
  home-server: home-server
  common-server: common-server

#mybatis
mybatis-plus:
  mapper-locations:  classpath:**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cc.likq.base.domain.entity,com.isxxc.domain.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: cn.jeefast.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    meta-object-handler: cc.likq.config.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: cn.jeefast.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

 #拦截器排除拦截
authenticationInterceptor:
  #拦截器排除拦截路径(方法)
  excludeClassMethodList:
